from reportlab.platypus import *
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from datetime import datetime
import glob
import os

OUTPUT = "/home/kali/Fiji-GodsEye/reports/NAYADRA_Operational_Briefing.pdf"

LOGO = "/home/kali/Fiji-GodsEye/assets/branding/nayadra_insignia.png"

SCREENSHOTS = "/home/kali/Fiji-GodsEye/assets/screenshots/*.png"

doc = SimpleDocTemplate(
    OUTPUT,
    pagesize=A4,
    rightMargin=40,
    leftMargin=40,
    topMargin=40,
    bottomMargin=28
)

styles = getSampleStyleSheet()
story = []

# =====================================
# COVER PAGE
# =====================================

try:
    logo = Image(LOGO, width=220, height=220)
    story.append(logo)
except:
    pass

story.append(Spacer(1,20))

title = Paragraph(
    "<font size=28><b>NA.YADRA</b></font>",
    styles["Title"]
)

subtitle = Paragraph(
    "<font size=16><b>Operational Maritime Intelligence Briefing</b></font>",
    styles["Heading2"]
)

story.append(title)
story.append(subtitle)

story.append(Spacer(1,25))

warning = Paragraph(
    "<font color='red'><b>FOR GOVERNMENT, CUSTOMS, LAW ENFORCEMENT AND REGIONAL SECURITY USE</b></font>",
    styles["BodyText"]
)

story.append(warning)

story.append(PageBreak())

# =====================================
# EXECUTIVE SUMMARY
# =====================================

summary = """
NA.YADRA is a Pacific-focused maritime intelligence and operational
awareness platform designed to support:

• Counter-narcotics monitoring
• Maritime domain awareness
• Vessel anomaly detection
• Dark vessel monitoring
• Cross-zone vessel tracking
• Regional operational intelligence
• AIS gap analysis
• Threat scoring and intelligence fusion

The platform combines AIS vessel intelligence, operational alerts,
satellite overlays, and real-time monitoring into a unified
intelligence environment.
"""

story.append(Paragraph(summary, styles["BodyText"]))

story.append(Spacer(1,25))

# =====================================
# CAPABILITY TABLE
# =====================================

data = [
    ["Capability", "Operational Status"],
    ["Live AIS Vessel Tracking", "ACTIVE"],
    ["Threat Scoring Engine", "ACTIVE"],
    ["Cross-Zone Tracking", "ACTIVE"],
    ["Dark Vessel Monitoring", "ACTIVE"],
    ["LOITERING Detection", "ACTIVE"],
    ["Rendezvous Detection", "ACTIVE"],
    ["Operational Alerts", "ACTIVE"],
    ["Satellite Overlay", "TESTING"],
]

table = Table(data, colWidths=[300,180])

table.setStyle(TableStyle([
    ('BACKGROUND',(0,0),(-1,0),colors.black),
    ('TEXTCOLOR',(0,0),(-1,0),colors.white),
    ('GRID',(0,0),(-1,-1),1,colors.grey),
    ('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),
]))

story.append(table)

story.append(PageBreak())

# =====================================
# SCREENSHOTS SECTION
# =====================================

story.append(Paragraph(
    "<font size=20><b>Operational Screenshots</b></font>",
    styles["Heading1"]
))

story.append(Spacer(1,20))

images = glob.glob(SCREENSHOTS)

for img in images:

    try:
        story.append(Image(img, width=480, height=260))
        story.append(Spacer(1,20))

        filename = os.path.basename(img)

        story.append(
            Paragraph(
                f"<b>{filename}</b>",
                styles["BodyText"]
            )
        )

        story.append(PageBreak())

    except:
        pass

# =====================================
# FUTURE ROADMAP
# =====================================

roadmap = """
<b>Future Development Roadmap</b><br/><br/>

• AI-assisted anomaly detection<br/>
• Multi-agency intelligence sharing<br/>
• Pacific regional threat network<br/>
• Satellite radar integration<br/>
• Predictive vessel route analysis<br/>
• Mobile operational dashboard<br/>
• Automated incident reporting<br/>
• SMS and email intelligence alerts<br/>
"""

story.append(Paragraph(roadmap, styles["BodyText"]))

story.append(Spacer(1,30))

timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

footer = Paragraph(
    f"<font size=10>Generated by NA.YADRA Intelligence System | {timestamp}</font>",
    styles["Italic"]
)

story.append(footer)

doc.build(story)

print(f"[+] OPERATIONAL BRIEFING GENERATED: {OUTPUT}")
